### ISSUE TITLE
在群人数上千的情况下邀请一人进群后，再次点开群资料界面卡顿。

### ISSUE THREAD

**Issue by haiwunsiang** [netease-kit/NIM_PC_Demo#100]
此时任务管理器占用，单核心满载，内存占用增加。在PC端上加员工入群时，非常占用时间，向官方请求优化。

**Comment by nmgwddj** [comment]
已关注该问题，近期会进行优化。

**Comment by haiwunsiang** [comment]
近几天优化的版本#头像下载频繁投递任务导致 UI 线程假死#问题依然存在。

**Comment by nmgwddj** [comment]
> 

develop 分支代码还在开发中，请勿投入生产使用。

**Comment by nmgwddj** [comment]
> 此时任务管理器占用，单核心满载，内存占用增加。在PC端上加员工入群时，非常占用时间，向官方请求优化。

对于首次打开邀请联系人页面卡顿问题，我还在考虑存储联系人列表插入和查询的最优方案。目前性能损耗主要在于联系人按首字母分组后的查询效率上。

您反馈的邀请后重新打开卡顿的问题，是因为全局的联系人窗口在邀请成员点击确定或者取消后窗口被销毁了，再次点开还会重新加载联系人列表。对此做了一些简单的优化。

**Comment by haiwunsiang** [comment]
请问Mac版本的桌面端源码有开源嘛。

**Comment by nmgwddj** [comment]
> 请问Mac版本的桌面端源码有开源嘛。github上macos的开源demo已经是4年前的。

因为 UI 框架不同，macOS 并没有提供示例 Demo，您可以考虑使用跨平台 UI 方案或者前端方案替代。
