### ISSUE TITLE
怎么部署

### ISSUE THREAD

**Issue by WudideGuokaihui** [netease-kit/NIM_PC_Demo#111]

**Comment by nmgwddj** [comment]
无法明确了解清楚您的问题是什么，如果您可以进一步描述清楚您所想要表达的问题，在问题描述中写清问题后重新打开此问题。

**Comment by WudideGuokaihui** [comment]
刚开始通过vs2017克隆源码到本地之后无法编译，最后通过Clion克隆到本地之后编译通过后在登陆界面无法注册账号导致不能登陆，找不到注册账号这个方法在哪里进行修改

**Comment by nmgwddj** [comment]
账号注册功能因历史被滥用，已经将注册能力禁止掉，修改可参考：https://github.com/netease-kit/NIM_PC_Demo/blob/master/app_sdk/app_sdk_interface.cpp#L140
