### ISSUE TITLE
VS2019下编译提示ErrorCode:MSB8020: 无法找到 Visual Studio 2013 - Windows XP 的生成工具

### ISSUE THREAD

**Issue by weipingQin** [netease-kit/NIM_PC_Demo#112]
build with virstual Studio 2019 throw this error like the picture ,在VS2019下该如何编译
![WindowsSDK不支持](https://github.com/netease-kit/NIM_PC_Demo/assets/9006169/3556a2e8-e242-47e3-b921-e775b546efe4)

**Comment by nmgwddj** [comment]
我想您可能提交错了位置，该工程没有任何使用 VS2013 工具链的项目。请先确保您的问题与该项目有关联，如问题描述有误请更正问题后重新打开此 issue。
