### ISSUE TITLE
vs2019编译sqlite3时报错

### ISSUE THREAD

**Issue by dengwant** [netease-kit/NIM_PC_Demo#114]
vs2019 环境执行cmake -Bbuild -AWin32 -DCMAKE_BUILD_TYPE=Debug 
有如下错误，错误尝试修改了下，但是重新执行上边的命令就覆盖掉了，有什么办法解决
<img width="844" alt="微信图片_20241031153437" src="https://github.com/user-attachments/assets/58bd58a2-4698-4f88-af4d-a375da3ab6ca">

**Comment by pixeloverflow** [comment]
编辑conanfile.py文件，修改32行sqlite版本为3.36.0, 如下
`self.requires("sqlite3/3.36.0")`

**Comment by nmgwddj** [comment]
> 编辑conanfile.py文件，修改32行sqlite版本为3.36.0, 如下 `self.requires("sqlite3/3.36.0")`

感谢提供解决方案。



> vs2019 环境执行cmake -Bbuild -AWin32 -DCMAKE_BUILD_TYPE=Debug 有如下错误，错误尝试修改了下，但是重新执行上边的命令就覆盖掉了，有什么办法解决 <img alt="微信图片_20241031153437" width="844" src="https://private-user-images.githubusercontent.com/7866670/381864878-58bd58a2-4698-4f88-af4d-a375da3ab6ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzI2MDUsIm5iZiI6MTczMDg3MjMwNSwicGF0aCI6Ii83ODY2NjcwLzM4MTg2NDg3OC01OGJkNThhMi00Njk4LTRmODgtYWY0ZC1hMzc1ZGEzYWI2Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDZUMDU1MTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWU2ODc1ZGNjMzI2YWJiYjYxOGJmNDk2ZGUzNjAxYTNkOTVlNDYzNTIxNDIzNjY4YWRkODQyNmJiOTU1MWQwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1ulDNvS7RAy7Nl0IAFJjsu4-__-S3iowq-7YAWqyglU">

我们安装的环境可能有部分差异，由于版权问题，我只能在安装了 Visual Studio Build Tools 2019 的环境下测试，所以命中到这个问题。我会考虑找机器安装社区版来尝试重现并修复问题。

如果两位有兴趣，可以提交 PR 到 develop 分支中帮我们修复该问题，再次感谢。
