### ISSUE TITLE
缺少资源文件

### ISSUE THREAD

**Issue by szdyg** [netease-kit/NIM_PC_Demo#67]
编译环境：
vs2017
cmake 3.20.5
缺少afxres.h
![image](https://user-images.githubusercontent.com/18255173/123132054-e3578c00-d480-11eb-8917-4c84daa930f6.png)

**Comment by nmgwddj** [comment]
![2021-06-24_09-37-11](https://user-images.githubusercontent.com/13995319/123189114-cdbd8300-d4cf-11eb-9552-ad61e79a844e.png)
 Visual Studio 安装时，将 MFC 组件安装上。实际 rc 文件里面引入这个头文件意义不大，可以删除。

**Comment by szdyg** [comment]
可以了，3q
