### ISSUE TITLE
项目初始化时CMakeLists.txt出现问题

### ISSUE THREAD

**Issue by AHESoft** [netease-kit/NIM_PC_Demo#74]
CMakeLists.txt第37行NIM_CrossPlatform_SDK_v8.7.0.zip的下载有问题，项目初始化时下载到build/下的是空文件，导致第98行找不到文件，继而引起100行报错’ADD_SUBDIRECTORY given source "wrapper" which is not an existing directory.‘
将第37行改为：
SET(NIM_CROSS_PLATFORM_SDK_URL "https://yx-web-nosdn.netease.im/package/1629860104/NIM_CrossPlatform_SDK_v8.7.0.zip")
可能有助于解决此问题

**Comment by nmgwddj** [comment]
@AHESoft 感谢反馈问题，您可以将修复以 PR 方式提交到 develop 分支，在审核后我们会进行合并。
您可以使用如下地址来下载 SDK 包：http://yx-web.nos.netease.com/package/1629860104/NIM_CrossPlatform_SDK_v8.7.0.zip（非 https）
