### ISSUE TITLE
vs2019编译不过去

### ISSUE THREAD

**Issue by sayyoume** [netease-kit/NIM_PC_Demo#79]
vs2019找不到  std::_Ref_count_obj

**Comment by nmgwddj** [comment]
暂不支持 VS2019 编译

**Comment by haiwunsiang** [comment]
我测试8.3.1是可以vs2019编译的。注意不是master。

**Comment by nmgwddj** [comment]
> 我测试8.3.1是可以vs2019编译的。注意不是master。

依赖的一些三方库使用的是 VS2017 v141 工具链编译的，如果您使用 VS2019，需要使用 v141 工具链才可以。
