### ISSUE TITLE
如何将demo改为适配自己的应用服务器

### ISSUE THREAD

**Issue by haiwunsiang** [netease-kit/NIM_PC_Demo#80]
在代码里找到了appkey 也去掉了password的md5加密，编译出来任然无法登录。
抓包看到demo登录时和103.129.225.216的服务器发起了tcp链接，
但我在代码里搜索不到这个地址。向大牛们请教下，更改哪处的代码
能实现登录自己搭建的应用服务器。

**Comment by haiwunsiang** [comment]
刚刚在sdk_pro.cpp发现了一些注释，但是和login似乎没有关系。
static const std::string cmd_register_account = "/api/createDemoUser";//注册账号
	static const std::string cmd_get_chatroomlist = "/api/chatroom/homeList";//获取聊天室列表
	static const std::string cmd_get_chatroomaddress = "/api/chatroom/requestAddress";//获取聊天室连接地址

**Comment by nmgwddj** [comment]
> 刚刚在sdk_pro.cpp发现了一些注释，但是和login似乎没有关系。 static const std::string cmd_register_account = "/api/createDemoUser";//注册账号 static const std::string cmd_get_chatroomlist = "/api/chatroom/homeList";//获取聊天室列表 static const std::string cmd_get_chatroomaddress = "/api/chatroom/requestAddress";//获取聊天室连接地址

IM Login 阶段并不是链接的应用服务器，而是我们的公有云 IM 服务器，您要连接应用服务器取什么内容还请描述清楚，这样方便我们帮助您寻找关键代码。

**Comment by haiwunsiang** [comment]
> > 刚刚在sdk_pro.cpp发现了一些注释，但是和login似乎没有关系。 static const std::string cmd_register_account = "/api/createDemoUser";//注册账号 static const std::string cmd_get_chatroomlist = "/api/chatroom/homeList";//获取聊天室列表 static const std::string cmd_get_chatroomaddress = "/api/chatroom/requestAddress";//获取聊天室连接地址
> 
> IM Login 阶段并不是链接的应用服务器，而是我们的公有云 IM 服务器，您要连接应用服务器取什么内容还请
