### ISSUE TITLE
功能请求，希望官方能在demo中添加聊天列表置顶的功能。

### ISSUE THREAD

**Issue by yipyeukyi** [netease-kit/NIM_PC_Demo#84]
在网络上查找没有找到duilib置顶聊天列表的功能，向官方求助。

**Comment by nmgwddj** [comment]
该功能内部已经有实现代码，最近会提交上来。

**Comment by yipyeukyi** [comment]
万分感谢，我做了向服务器post数据，接收返回json的部分，晚上新开一个自建仓库同步，使用curl和jsoncpp库实现了从appserver拉取accid和token。

**Comment by yipyeukyi** [comment]
> 该功能内部已经有实现代码，最近会提交上来。

新年好，有增加置顶功能的打算嘛，可提供捐赠。

**Comment by nmgwddj** [comment]
https://github.com/netease-kit/NIM_PC_Demo/commit/694f106510cec689c196bb199c215c2b200cd7f3
功能已添加。
