### ISSUE TITLE
点击登录崩溃

### ISSUE THREAD

**Issue by tracytracy123** [netease-kit/NIM_PC_Demo#86]
<img width="1167" alt="image_2022-01-03_15-50-59" src="https://user-images.githubusercontent.com/80315407/147908982-9bb1fd91-2059-4dc6-aece-337a467560dc.png">

不知道是不是缺少ceflib.dll，但在bin/cef/目录下有nim_libcef.dll

**Comment by nmgwddj** [comment]
请描述清楚您该问题发生的重现步骤。

**Comment by tracytracy123** [comment]
@nmgwddj ，编译运行，点击登录按钮，就报错了

**Comment by tracytracy123** [comment]
<img width="888" alt="image_2022-01-04_09-18-21" src="https://user-images.githubusercontent.com/80315407/147997297-99cb5dbc-c004-411f-bf45-a3f7d12eddd2.png">

**Comment by nmgwddj** [comment]
> @nmgwddj ，编译运行，点击登录按钮，就报错了

1、您使用的是哪个分支的代码？
2、使用 clone 方式还是下载 zip 包的方式获取代码？
3、执行 CMake 的初始化命令是什么？
4、执行编译的命令是什么？
5、是否有改动过代码？
6、登录的测试账号是什么？

编译、登录这是最基础的测试流程，这些代码一定是通过的。反馈问题时尽量站在看问题人的角度去考量一下，自己描述的问题别人能否看明白，能否根据你的步骤重现问题？思考为什么别人没有反馈过类似问题，如果有反馈你们操作的共同点在哪里？

**Comment by tracytracy123** [comment]
@nmgwddj ，8.3.1版本，直接下载的zip，不是cmake构建的，直接点绿色三角运行编译啊，启动登录界面，正常，然后我点击了一下按钮，就说未加载libcef.dll.pdb，是不是我缺少这个libcef.dll呢

**Comment by xiaoge136** [comment]
> 

这个版本需要填写appkey才可以登录，如果没有特殊要求的话，使用develop或者master分支
