### ISSUE TITLE
namespace "std" has no tag member named "_Ref_count_obj"

### ISSUE THREAD

**Issue by Lincong-pro** [netease-kit/NIM_PC_Demo#88]
1>async_do_modal.cpp
1>C:\Users\lovely-boy\Desktop\NIM_PC_Demo\tool_kits\shared\modal_wnd\async_modal_runner.h(49,20): error C2039: '_Ref_count_obj': is not a member of 'std'
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\stack(20): message : see declaration of 'std'
1>C:\Users\lovely-boy\Desktop\NIM_PC_Demo\tool_kits\shared\modal_wnd\async_modal_runner.h(49,34): error C3856: '_Ref_count_obj': symbol is not a class template
1>C:\Users\lovely-boy\Desktop\NIM_PC_Demo\tool_kits\shared\modal_wnd\async_modal_runner.h(49,51): error C2098: unexpected token after data member 'AsyncModalRunner'
1>C:\Users\lovely-boy\Desktop\NIM_PC_Demo\tool_kits\shared\modal_wnd\async_modal_runner.h(49,51): error C2059: syntax error: '>'
1>async_modal_runner.cpp
1>C:\Users\lovely-boy\Desktop\NIM_PC_Demo\tool_kits\shared\modal_wnd\async_modal_runner.h(49,20): error C2039: '_Ref_count_obj': is not a member of 'std'
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\stack(20): message : see declaration of 'std'
1>C:\Users\lovely-boy\Desktop\NIM_PC_Demo\tool_kits\shared\modal_wnd\async_modal_runner.h(49,34): error C3856: '_Ref_count_obj': symbol is not a class template
1>C:\Users\lovely-boy\Desktop\NIM_PC_Demo\tool_kits\shared\modal_wnd\async_modal_runner.h(49,51): error C2098: unexpected token after data member 'AsyncModalRunner'
1>C:\Users\lovely-boy\Desktop\NIM_PC_Demo\tool_kits\shared\modal_wnd\async_modal_runner.h(49,51): error C2059: syntax error: '>'
1>Generating Code...
1>Done building project "shared.vcxproj" -- FAILED.

**Comment by Lincong-pro** [comment]
It occurred some question when compiling the base>shared library.However,I find it is C14 Standard.How do I solve the question?

**Comment by Lincong-pro** [comment]
你好，请问可以回答你们怎么解决这个问题的吗

**Comment by nmgwddj** [comment]
Try to use develop branch.

**Comment by Lincong-pro** [comment]
Yeah,I've already solved the problem!Thank you!

**Comment by xiaoriri-cloud** [comment]
> 是的，我已经解决了！谢谢！

可以问下怎么解决的吗我用最新版vs也遇到了
