### ISSUE TITLE
求指导实现profile显示的accid和用户名复制

### ISSUE THREAD

**Issue by yipyeukyi** [netease-kit/NIM_PC_Demo#94]
实际使用过程中发现profile页面显示的好友明和accid是不可能选中和复制的，如何才能使其可被选中和复制。

**Comment by nmgwddj** [comment]
增加一个 copy icon 用于点击复制。

**Comment by yipyeukyi** [comment]
//给出参考示例

#include <stdio.h> 
#include <stdlib.h> 
#include <string.h> 
#include <Windows.h> 
/*将字符串写入到剪切板*/ 
int setClipbar(const char *data){ 
    int contentSize = strlen(data) + 1; 
    HGLOBAL hMemory; LPTSTR lpMemory; 
    if(!OpenClipboard(NULL)) return 0;/* 打开剪切板 */ 
    if(!EmptyClipboard()) return 0; /* 清空剪切板 */ 
    if(!(hMemory = GlobalAlloc(GMEM_MOVEABLE, contentSize))) return 0;/* 对剪切板分配内存 */ 
    if(!(lpMemory = (LPTSTR)GlobalLock(hMemory))) return 0;/* 锁定内存区域 */ 
    memcpy_s(lpMemory, contentSize, data, contentSize);    /* 复制数据到内存区域 */ 
    GlobalUnlock(hMemory);                                 /* 解除内存锁定 */ 
    if(!SetClipboardData(CF_TEXT, hMemory)) return 0;      /* 设置剪切板数据 */ 
    printf("成功复制【%s】到剪切板，字符串长度为%d。\n",data,contentSize); 
    CloseClipboard();/* 关闭剪切板 */ 
    return 1; 
} 
int main(){ 
	setClipbar("abcdefg"); 
	getchar(); 
	return 0; 
}

**Comment by nmgwddj** [comment]
duilib richedit 控件有提供全局的将内容设置到剪切板的实现。
