### ISSUE TITLE
关于转发性能的问题

### ISSUE THREAD

**Issue by yipyeukyi** [netease-kit/NIM_PC_Demo#95]
dev版本使用转发将消息转发给300个人时总共用时5min以上，不知是否是因为我使用windows低端平板的缘故，测试CPU是N4120、CPU占用60%，耗时间5分钟以上完成全部转发。共测试三次使用的时间一样多。

另外将消息转发给到群主中时，第一次转发会卡顿之后流畅，具体原因未知，猜测是转发时候调用的附近用户的头像导致。该问题在8.2版本中似乎并不严重，我会尝试屏蔽用户头像。

**Comment by nmgwddj** [comment]
合并处理：https://github.com/netease-kit/NIM_PC_Demo/issues/96
